### ISSUE TITLE
Demo page

### ISSUE THREAD

**Issue by theideaofnorth2** [reactify/react-player-controls#1]
Hello and thanks for the package!

I've been developing my own audio controls because I couldn't find a package that suits my needs, but yours seems to be modular enough for designers to create what they need, so thanks a lot for exposing this publicly. 

One thing that seems to be missing in your project is an examples / demo page, so that people can quickly see if your components are what they need.

Would it be possible for you to display a few examples on a demo page? One simple way to do this could be to use the brand new feature that Github released a few days ago to publish pages with a "docs" directory: https://github.com/blog/2228-simpler-github-pages-publishing

**Comment by alexanderwallin** [comment]
Hi @theideaofnorth2!

Thanks for the feedback, glad to hear it might fit your needs. A demo page is a good idea, and is already half-done locally. I'll get this going and notify you when it's up!

**Comment by theideaofnorth2** [comment]
Great thanks @alexanderwallin , can't wait to see it :)

**Comment by alexanderwallin** [comment]
So @theideaofnorth2, you can check it out at http://reactify.github.io/react-player-controls/

Any feedback is welcome!

**Comment by vkammerer** [comment]
Thanks @alexanderwallin (I am also @theideaofnorth2 :) ) it's looking really good! I will integrate at least the volume control and the time marker and let you know if I see bugs or room for improvement.

**Comment by alexanderwallin** [comment]
Haha, nice. Alright, that sounds perfect!
