### ISSUE TITLE
Buttons not showing

### ISSUE THREAD

**Issue by pakerfeldt** [reactify/react-player-controls#17]
This is likely a stupid question from someone who started playing around with react few days ago. However, I can't get the playback icons to show. What I see is only an empty button. I installed the npm package and created my own `Component` in which I intend to wrap all the playback controls. Inside I do `import { PlayButton, PauseButton } from 'react-player-controls'` and add two buttons inside a div in its render function like so:
```
render() {
    return (
      <div>
        <PlayButton isEnabled={true} onClick={this.playHandler} />
        <PauseButton onClick={this.pauseHandler} />
      </div>
    );
  }
```

Is there anything additional I need to do to make sure the svg files are bundled with the site?

**Comment by pakerfeldt** [comment]
Realized there weren't any default styles included.

**Comment by alexanderwallin** [comment]
Sorry for the inconvenience, @pakerfeldt. It is indeed confusing that nothing shows up when you include the components without applying any styles.

There is a [milestone addressing styles](https://github.com/reactify/react-player-controls/milestone/1).
