### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by vkammerer** [reactify/react-player-controls#4]
Hello,

The README could add more information so that users know:
- that the package is published on npm. it could be done by displaying a section "Installation" and add the line `npm i react-player-controls`
- how to import it and use it within an application. A line like `import { PlayButton, PauseButton, PrevButton, NextButton, PlaybackControls } from 'react-player-controls'` before the first examples should be enough.

I can submit a PR for it if you want?

**Comment by alexanderwallin** [comment]
Brilliant, go ahead!

**Comment by alexanderwallin** [comment]
* It is not clear nor exemplified that you can put anything you want inside the components (`children`), and that the icons are just for default.

**Comment by vkammerer** [comment]
Indeed.
Also, for the bottom part of the README, what do you think about:
- renaming the "Development" section to "Contribute"
- making three subsections "dev", "build" and "test" with the CLI commands tu run
- adding a line that mentions that any PR should be open only if tests have passed locally
- removing the last section about publishing, as it is solely the role of the maintainer, and that the README could be more directed at users and contributors.

**Comment by alexanderwallin** [comment]
I think this README will end up at Tate Modern one day. 😊

**Comment by vkammerer** [comment]
lol, such a british thing to say ;)

**Comment by alexanderwallin** [comment]
Do you want to PR those last four changes or should I?

**Comment by vkammerer** [comment]
sure
